---
apiVersion: v1
kind: Namespace
metadata:
   name: dev
   labels:
      name: dev
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-quota
  namespace: dev
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-quota
  namespace: dev
  labels:
    app: frontend
  annotations:
    kubernetes.io/change-cause: "Deployment respetando quotas del NS dev"
# Es el manifiesto del ReplicaSet
spec:
  replicas: 3
  # revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: frontend
  template:
    # Manifiesto de los Pods
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          limits:
            memory: 1Gi
            cpu: 1
          requests:
            memory: 0.5Gi
            cpu: 0.5
        ports:
        - containerPort: 80
---
