apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-backend
  labels:
    type: local
    app: backend
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/denisrocher/Library/Mobile Documents/com~apple~CloudDocs/capacitacion/Docker/volumes/VolumesHostPath/backend"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-frontend
  labels:
    type: local
    app: frontend
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/denisrocher/Library/Mobile Documents/com~apple~CloudDocs/capacitacion/Docker/volumes/VolumesHostPath/frontend"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim-frontend
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: "local"
      app: "frontend"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim-backend
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: "local"
      app: "backend"