apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test-frontend
  labels:
    app: frontend
  annotations:
    kubernetes.io/change-cause: "Deployment Initial del servicio frontend"
# Es el manifiesto del ReplicaSet
spec:
  replicas: 3
  # revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: frontend
  template:
    # Manifiesto de los Pods
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-frontend
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80