apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test-backend
  labels:
    app: backend
  annotations:
    kubernetes.io/change-cause: "Deployment Initial del servicio backend"
# Es el manifiesto del ReplicaSet
spec:
  replicas: 3
  # revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: backend
  template:
    # Manifiesto de los Pods
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-backend
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80