apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  labels:
    app: frontend
  annotations:
    kubernetes.io/change-cause: "Se corrige imagen de nginx:alpine"
# Es el manifiesto del ReplicaSet
spec:
  replicas: 3
  # revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: frontend
  template:
    # Manifiesto de los Pods
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80