apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: frontend
data:
  test: hola
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a configmap Index file </h1>
    </html
  nginx:
    server {
      listen       9090;
      server_name  localhost;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    } 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  labels:
    app: frontend
  annotations:
    kubernetes.io/change-cause: "Deployment con configmap de nginx:alpine"
# Es el manifiesto del ReplicaSet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    # Manifiesto de los Pods
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
          - name: nginx-vol
            mountPath: /etc/nginx/conf.d/
          - name: nginx-index
            mountPath: /usr/share/nginx/html/
      volumes:
        - name: nginx-vol
          configMap:
            name: nginx-config
            items:
            - key: nginx
              path: default.conf
        - name: nginx-index
          configMap:
            name: nginx-config
            items:
            - key: index.html
              path: index.html
