apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-vars
  labels:
    app: frontend
data:
  test: hola
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a configmap Index file con Variables de entorno </h1>
    </html>
  db_host: dev.host.local
  db_user: dev_user
  script: |
    echo DB HOST es $DB_HOST y DB USER es $DB_USER > /usr/share/nginx/html/test.html
  nginx:
    server {
      listen       9090;
      server_name  localhost;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    } 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  labels:
    app: frontend
  annotations:
    kubernetes.io/change-cause: "Deployment con Variables de entorno"
# Es el manifiesto del ReplicaSet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    # Manifiesto de los Pods
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:alpine

          env:
            # Define the environment variable
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  # The ConfigMap containing the value you want to assign to DB_HOST
                  name: nginx-vars
                  # Specify the key associated with the value
                  key: db_host           
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  # The ConfigMap containing the value you want to assign to DB_USER
                  name: nginx-vars
                  # Specify the key associated with the value
                  key: db_user  
          volumeMounts:
          - name: nginx-index
            mountPath: /usr/share/nginx/html/
          - name: nginx-script
            mountPath: /opt/
          - name: nginx-vol
            mountPath: /etc/nginx/conf.d/      
      volumes:
        - name: nginx-index
          configMap:
            name: nginx-vars
            items:
            - key: index.html
              path: index.html
        - name: nginx-script
          configMap:
            name: nginx-vars
            items:
            - key: script
              path: script.sh
        - name: nginx-vol
          configMap:
            name: nginx-vars
            items:
            - key: nginx
              path: default.conf
