---
apiVersion: v1
kind: Namespace
metadata:
  name: ci
  labels:
    name: ci
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-k8s-hands-on
  namespace: ci
  labels:
    app: backend
  annotations:
    kubernetes.io/change-cause: "Deployment servicio backend en namespace ci"
# Es el manifiesto del ReplicaSet
spec:
  replicas: 3
  # revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: backend
  template:
    # Manifiesto de los Pods
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: k8s-hands-on:v2
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: backend-k8s-hands-on
  namespace: ci
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31000
      targetPort: 9090
---