apiVersion: v1
kind: Pod
metadata:
  name: test-dev-min-max
  namespace: dev
  labels:
    app: backend
    env: dev
spec:
  containers:
  - name: container1
    image: nginx:alpine
    resources:
      limits:
        memory: 500M
        cpu: 0.5
      requests:
        memory: 400M
        cpu: 0.4
---
apiVersion: v1
kind: Pod
metadata:
  name: test-menos-min
  namespace: dev
  labels:
    app: backend
    env: dev
spec:
  containers:
  - name: container1
    image: nginx:alpine
    resources:
      limits:
        memory: 50Mi
        cpu: 50m
      requests:
        memory: 40Mi
        cpu: 30m
---
apiVersion: v1
kind: Pod
metadata:
  name: test-mas-max
  namespace: dev
  labels:
    app: backend
    env: dev
spec:
  containers:
  - name: container1
    image: nginx:alpine
    resources:
      limits:
        memory: 2Gi
        cpu: 2
      requests:
        memory: 1.5Gi
        cpu: 1.5
---