apiVersion: v1
kind: Pod
metadata:
  name: test-dev
  namespace: dev
  labels:
    app: backend
    env: dev
spec:
  containers:
  - name: container1
    image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: test-default
  labels:
    app: backend
    env: dev
spec:
  containers:
  - name: container1
    image: nginx:alpine