apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: backend
    env: dev
spec:
  containers:
  - name: container1
    image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: test2
  labels:
    app: backend
    env: dev
spec:
  containers:
  - name: container1
    image: nginx:alpine