apiVersion: v1
kind: Secret
metadata:
  name: mysecret-stringdata
  labels:
    app: frontend
type: Opaque
stringData:
  username: admin
  password: 123adm456
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: nginx:alpine
    env:
    - name: SECRET_USERNAME_TEST
      valueFrom:
        secretKeyRef:
          name: mysecret-stringdata
          key: username
    - name: SECRET_PASSWORD_TEST
      valueFrom:
        secretKeyRef:
          name: mysecret-stringdata
          key: password
    volumeMounts:
    - name: test
      mountPath: "/opt"
      readOnly: true
  volumes:
  - name: test
    secret:
      secretName: mysecret-stringdata
      items:
      - key: username
        path: user.txt
  restartPolicy: Never