apiVersion: v1
kind: Secret
metadata:
  name: mysecret-stringdata
  labels:
    app: frontend
type: Opaque
stringData:
  username: admin
  password: 123adm4563
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: frontend
spec:
  containers:
  - name: mypod
    image: nginx:alpine
    volumeMounts:
    - name: test
      mountPath: "/opt"
      readOnly: true
  volumes:
  - name: test
    secret:
      secretName: mysecret-stringdata
      items:
      - key: username
        path: user.txt